{
  "uid" : "a586f689754a2a7f",
  "name" : "test_broken",
  "fullName" : "test_pytest_allure.test_allure02#test_broken",
  "historyId" : "90c26e612040887e04163b9df2e39a9f",
  "time" : {
    "start" : 1653276474490,
    "stop" : 1653276474490,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "Exception: oops",
  "statusTrace" : "@allure.feature('test_broken') #模块名\n    def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\ntest_pytest_allure\\test_allure02.py:54: Exception",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "test_broken"
  }, {
    "name" : "parentSuite",
    "value" : "test_pytest_allure"
  }, {
    "name" : "suite",
    "value" : "test_allure02"
  }, {
    "name" : "host",
    "value" : "PC-20210510KUZF"
  }, {
    "name" : "thread",
    "value" : "13068-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_pytest_allure.test_allure02"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "a586f689754a2a7f.json",
  "parameterValues" : [ ]
}